/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.43
 * Generated at: 2025-07-10 04:47:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch04;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class form_005fmembership01_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>개인정보입력입니다!</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	Home > Join the Membership\r\n");
      out.write("	<form action=\"form_membership02.jsp\" name = \"person_info\" method = \"post\" >\r\n");
      out.write("	<fieldset style = \"width:330px\">\r\n");
      out.write("		<legend>개인 정보 입력</legend>\r\n");
      out.write("		아이디: <br>\r\n");
      out.write("		<input type = \"text\" name = \"id\"> <br><br>\r\n");
      out.write("		비밀번호: <br>\r\n");
      out.write("		<input type = \"text\" name = \"password\"> <br><br>\r\n");
      out.write("		이름: <br>\r\n");
      out.write("		<input type = \"text\" name = \"name\"> <br><br>\r\n");
      out.write("		\r\n");
      out.write("		연락처: <br>\r\n");
      out.write("		<select name = \"choice\" style = \"width:60px;height:20.5px\">\r\n");
      out.write("			<option value = \"skt\">SKT</option>\r\n");
      out.write("			<option value = \"kt\">KT</option>\r\n");
      out.write("			<option value = \"lg\">LG U+</option>			\r\n");
      out.write("		</select> \r\n");
      out.write("		<input type=\"text\" name=\"p1\" maxlength=\"3\" size = \"3\"> - \r\n");
      out.write("		<input type=\"text\" name=\"p2\" maxlength=\"3\" size = \"3\"> - \r\n");
      out.write("		<input type=\"text\" name=\"p3\" maxlength=\"3\" size = \"3\"> \r\n");
      out.write("		<br><br>\r\n");
      out.write("		성별: &nbsp; <input type = \"radio\" name = \"gender\" value=\"남성\">남 &nbsp; <input type = \"radio\" name = \"gender\"value=\"여성\">여 <br><br>\r\n");
      out.write("		\r\n");
      out.write("		취미: &nbsp; <input type = \"checkbox\" name = \"hobby\" value=\"운동\">운동\r\n");
      out.write("				&nbsp; <input type = \"checkbox\" name = \"hobby\" value=\"독서\">독서\r\n");
      out.write("				&nbsp; <input type = \"checkbox\" name = \"hobby\" value=\"여행\">여행\r\n");
      out.write("				&nbsp; <input type = \"checkbox\" name = \"hobby\" value=\"음악감상\">음악감상 <br><br>\r\n");
      out.write("				\r\n");
      out.write("		본인 소개: <br>\r\n");
      out.write("		<textarea name=\"introduce_area\" rows=\"3\" cols=\"50\" >\r\n");
      out.write("		</textarea> <br><br>\r\n");
      out.write("\r\n");
      out.write("		<div align=\"center\">\r\n");
      out.write("			<input type=\"submit\" value=\"가입하기\">\r\n");
      out.write("			&nbsp;&nbsp;\r\n");
      out.write("			<input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
